/*
    Team:
        Jordan Schalm   37955135
        David Julien    16997132
        Seerat Sekhon   35145135

    Project:
        Mastermind - An implementation of the classic Mastermind game.
*/

% Initialize
:-
	[mastermind_game, mastermind_setup],
	writeln('\n----MASTERMIND----\n'),
	writeln('Created by:'),
	writeln('    David Julien\n    Jordan Schalm\n    Seerat Sekhon\n'),
	writeln('Use "rules." to learn the rules of the game.'),
	writeln('Use "help." to learn how the game is played.'),
	writeln('Use "setup." to change the game settings.\n'),
	writeln('Use "start." to start the game.\n').

rules :-
	writeln('RULES:'),
	writeln('The classic game is played using:
- A decoding board, with a shield at one end covering a row of four large holes, and 10 additional rows containing four large holes next to a set of four small holes;
- Code pegs of six different colors, which will be placed in the large holes on the board; and
- Key pegs, some colored black, some white, which are flat-headed and smaller than the code pegs; they will be placed in the small holes on the board.\n'),
	writeln('In this virtual representation of the game:
- The shielded answer is an auto-generated list of 4 code pegs;
- The decoding board is represented as a series of guesses, where guesses are a list of 4 code pegs;
- The code peg colors are represented as a number between 1 and 6;
- The key pegs are represented as a "w" or "b", and will be returned in a list upon making a guess.\n'),
	writeln('You are the codebreaker, The codebreaker tries to guess the pattern generated by the codemaker (The computer), in both order and color, within 10 turns. Each guess is made by placing a row of code pegs on the decoding board. Once placed, the codemaker provides feedback by placing from zero to four key pegs in the small holes of the row with the guess. A colored or black key peg is placed for each code peg from the guess which is correct in both color and position. A white key peg indicates the existence of a correct color code peg placed in the wrong position.\n'),
	writeln('source: https://en.wikipedia.org/wiki/Mastermind_(board_game)\n').

help :-
	writeln('HELP:'),
	writeln('-Start the game with "start."'),
	writeln('-Make a guess by entering a list of 4 numbers within 1-6 and press enter. i.e. [1,2,3,6].'),
	writeln('-Hints will be returned as a list of w and b, where w indicates a correct colour but incorrect position, and b represents a correct color with a correct position.').